### ISSUE TITLE
锐捷web认证的适用吗？

### ISSUE THREAD

**Issue by BytePrince** [KumaTea/MentoHUST-SYSU-Guide#1]
如题，我们学校是web认证的，不知道是否适用。

**Comment by KumaTea** [comment]
应该不适用，但你也可以用[二进制文件](https://github.com/KumaTea/MentoHUST-SYSU-Guide/releases)试试看。

另：按照搜索结果，[Web认证](https://github.com/Letki/RuijiePortalLoginShellScript)应该比这个简单一些。

Issue 手滑误关已重开。
